# Generated by Django 3.0.6 on 2020-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200719_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
    ]
