# Generated by Django 3.0.6 on 2020-07-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
